"""books_table

Revision ID: ae2f6db54be3
Revises: 4193770d402b
Create Date: 2022-01-26 10:42:40.858914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ae2f6db54be3"
down_revision = "4193770d402b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "books",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=50), nullable=False),
        sa.Column("isbn", sa.BigInteger(), nullable=False),
        sa.Column("number_of_pages", sa.Integer(), nullable=False),
        sa.Column("published_date", sa.Date(), nullable=False),
        sa.Column("language", sa.String(length=2), nullable=False),
        sa.Column("info_link", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("isbn"),
    )
    op.create_table(
        "book_author",
        sa.Column("book_id", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["authors.id"],
        ),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["books.id"],
        ),
        sa.PrimaryKeyConstraint("book_id", "author_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("book_author")
    op.drop_table("books")
    # ### end Alembic commands ###
