"""change published_date nullable true

Revision ID: e778f9b093b9
Revises: 1c7ad1b3e599
Create Date: 2022-01-31 23:31:00.217721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e778f9b093b9"
down_revision = "1c7ad1b3e599"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "books", "published_date", existing_type=sa.DATE(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "books", "published_date", existing_type=sa.DATE(), nullable=False
    )
    # ### end Alembic commands ###
